feat(aws): Test workflow for deploying to AWS
projectNEWM/newm-web pull request #599
Opened 2024-04-22 06:34 UTC by jayvaznewm

2024-04-22 12:47 UTC, escobarjonatan approved these changes

2024-05-11 03:44 UTC, scandycuz commented on .github/workflows/cdk/jest.config.js
> +};
Any way to reference the `jest.config` at the top level of the repo, or does cdk require it's own file? Also, do you know how this file is used when deploying? Should it match the jest.config used locally?

2024-05-11 03:49 UTC, scandycuz commented on .vscode/settings.json
> +    "editor.defaultFormatter": "esbenp.prettier-vscode"
Was this intentional or required? We're currently using a formatter that combines prettier and eslint which seems to work well and is a bit more configurable.

2024-05-11 03:50 UTC, scandycuz commented on apps/marketplace/project.json
> +          "port": 3000
It would be good to leave the development port on 4200, so that each app can be run on a different port locally (although the back-end still needs CORS configured to support port 4200). The production port works as 3000 though.

2024-05-11 03:52 UTC, scandycuz requested changes
Thanks again for putting this together. Not sure if any of my changes require holding off merging the PR, but wanted to leave a review with a status of "Request changes", to hold off merging in case some of them would be good to make. I imagine the PR may just be for testing though.

2024-05-11 03:56 UTC, scandycuz commented on .github/workflows/cdk/package.json
> +}
Is it necessary to have a separate `package.json` file here? Nx seems to support having a single package.json file at the root of the repo, although I imagine cdk may require a separate one.

2024-05-11 03:59 UTC, scandycuz commented on apps/marketplace/Dockerfile
> +FROM node:20 as base
I know Jonatan, David, and I are currently using Node v18, but we could upgrade to 20 if it's recommended.

2024-05-11 21:47 UTC, jayvaznewm commented on .github/workflows/cdk/package.json
> +}
I am treating this cdk directory as a is a "mini-tool" only used to deploy into AWS - it coincidentally happens to be written in TypeScript.  Its small and single purpose, and I am not sure if it makes sense to integrate with the tooling of the actual project - so I kept the package.json separate - open to feedback tho.  Hopefully this CDK directory will be rarely touched

2024-05-11 21:47 UTC, jayvaznewm commented on apps/marketplace/Dockerfile
> +FROM node:20 as base
Given the rate of new nodejs versions and the backward compatibility I tend to go with the latest stable version - both work here - so no concerns with 18 either

2024-05-11 21:47 UTC, jayvaznewm commented on .github/workflows/cdk/jest.config.js
> +};
since the cdk project is small and single purpose - its unlikely we'll ever develop tests for it - so I just nuked it

2024-05-11 21:47 UTC, jayvaznewm commented on .vscode/settings.json
> +    "editor.defaultFormatter": "esbenp.prettier-vscode"
sorry - copy pasta - fixed now

2024-05-12 02:09 UTC, scandycuz commented on .github/workflows/cdk/jest.config.js
> +};
Sounds good. I mostly was just unsure if it was going to be running the app unit tests with that jest configuration, but it sounds like it would be for separate cdk related tests.

2024-05-12 02:10 UTC, scandycuz commented on .github/workflows/cdk/package.json
> +}
Having it separate sounds like it makes sense

2024-05-12 02:12 UTC, scandycuz commented on apps/marketplace/Dockerfile
> +FROM node:20 as base
Either way works for me. It looks like the default version on the Node.js website is currently 20, so upgrading is probably a good idea

2024-05-12 02:18 UTC, scandycuz approved these changes
LGTM!

2024-05-12 15:43 UTC, merged